version: 2
jobs:
  deploy:
    docker:
      - image: google/cloud-sdk:206.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: CircleCIでGCPにログインする
          command: |
            GOOGLE_PROJECT_ID=door-app-prod
            GCLOUD_SERVICE_KEY=${GCLOUD_SERVICE_KEY}
            echo ${GCLOUD_SERVICE_KEY} | base64 -i --decode > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project door-app-prod
            gcloud --quiet config set compute/zone asia-northeast1-a
            gcloud --quiet container clusters get-credentials door
      - run:
          name: test
          command: |
            kubectl config get-contexts
            kubectl apply -f ./istio.yaml
            kubectl apply -f ./production/namespace.yaml
            kubectl apply -f ./production/gateway.yaml
      - run:
          name: home 初回のみ
          command: |
            kubectl apply -f ./production/home.yaml

workflows:
  version: 2
  test:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master